-- Espelho das inscrições atuais do LetzPlay: 253 pessoas e 277 inscrições.
create table if not exists public.athlete_registrations (
  id uuid primary key default gen_random_uuid(), athlete_id uuid not null references public.athletes(id) on delete cascade,
  team_id uuid references public.teams(id) on delete cascade, team_name text not null,
  category_name text not null check (category_name in ('60+', '40+', 'E', 'D', 'C', 'B', 'A')),
  letzplay_profile text, created_at timestamp default now(), updated_at timestamp default now(), unique (athlete_id, category_name)
);
create index if not exists athlete_registrations_team_category_idx on public.athlete_registrations (team_id, category_name);
alter table public.athlete_registrations enable row level security;
drop policy if exists athlete_registrations_public_read on public.athlete_registrations;
create policy athlete_registrations_public_read on public.athlete_registrations for select to anon, authenticated using (true);
grant select on public.athlete_registrations to anon, authenticated;
grant select, insert, update, delete on public.athlete_registrations to service_role;

insert into public.athletes (team_id, team_name, athlete_name, gender)
select t.id, v.team_name, v.athlete_name, v.gender from (values
  ('Portugal', 'Pedro Lucas', 'Masculino'), ('Portugal', 'Filipe Gomes', 'Masculino'),
  ('Brasil', 'Ana Gabriela', 'Feminino'), ('Brasil', 'Agar Souza', 'Feminino'),
  ('Brasil', 'Taline Mangolin', 'Feminino')
) as v(team_name, athlete_name, gender) join public.teams t on t.team_name = v.team_name
where not exists (select 1 from public.athletes a where a.team_id = t.id and lower(trim(a.athlete_name)) = lower(trim(v.athlete_name)));

delete from public.athlete_registrations;
with source(athlete_name, team_name, category_name, letzplay_profile) as (values
  ('Guilherme Valias Schmitt', 'Paraguai', '40+', 'https://letzplay.me/GuilhermeSchmitt4'),
  ('Karina Farah', 'Paraguai', '40+', 'https://letzplay.me/KarinaFarah'),
  ('Sonyangela Imai Rossi', 'Paraguai', '40+', 'https://letzplay.me/SonyangelaRossi'),
  ('Mariane Ziliotto', 'Paraguai', '40+', 'https://letzplay.me/MarianeZiliotto'),
  ('Camilo Cabral', 'Paraguai', '40+', 'https://letzplay.me/CamiloCabral'),
  ('Thiago Alfredo Pereira da Silva', 'Paraguai', '40+', 'https://letzplay.me/ThiagoSilva4'),
  ('Luiz Lepri Jr', 'Cabo Verde', '40+', 'https://letzplay.me/Luizleprijr'),
  ('Sara Cristina Bordim Crespo', 'Cabo Verde', '40+', 'https://letzplay.me/SaraCristinaCrespo'),
  ('Everton Hernandes', 'Cabo Verde', '40+', 'https://letzplay.me/EvertonHernandes'),
  ('Andressa Spessatto', 'Portugal', '40+', 'https://letzplay.me/AndressaSpessatto'),
  ('Vanessa Nava', 'Portugal', '40+', 'https://letzplay.me/VanessaNava2'),
  ('Fábio Spessatto', 'Portugal', '40+', 'https://letzplay.me/Fabiospessatto1'),
  ('Fabiana Paiva', 'Argentina', '40+', 'https://letzplay.me/FabianaPaiva1'),
  ('Patty Nascimento', 'Noruega', '40+', 'https://letzplay.me/PattyNascimento'),
  ('Daniela Lara Lara', 'Noruega', '40+', 'https://letzplay.me/DanielaLaraLara'),
  ('Hugo Okuma', 'Noruega', '40+', 'https://letzplay.me/HugoOkuma1'),
  ('Thiago Garcia', 'Noruega', '40+', 'https://letzplay.me/ThiagoGarcia07'),
  ('Alex Eiras', 'Aruba', '40+', 'https://letzplay.me/Alexeiras1'),
  ('Rafael Funayama', 'Aruba', '40+', 'https://letzplay.me/RafaelFunayama5'),
  ('Alessandra Ziliotto', 'Aruba', '40+', 'https://letzplay.me/AlessandraZiliotto'),
  ('Adriele Almeida Ribeiro', 'Aruba', '40+', 'https://letzplay.me/AdrieleJanainadeAlmeidaRibeiro'),
  ('Marcelo Silva', 'Aruba', '40+', 'https://letzplay.me/MarceloSilva261'),
  ('Dheferson Ribeiro', 'USA', '40+', 'https://letzplay.me/DhefersonRibeiro'),
  ('Diogo Marchi', 'USA', '40+', 'https://letzplay.me/DiogoMarchi'),
  ('Alberto Vinícius Rodrigues Lima', 'Paraguai', '60+', 'https://letzplay.me/AlbertoViniciusLima'),
  ('Daniel Felipe Faleiro', 'Paraguai', '60+', 'https://letzplay.me/DanielFaleiro'),
  ('Faena Gabriela Ehlers', 'Paraguai', '60+', 'https://letzplay.me/faenaehlers'),
  ('Luísa Farah', 'Paraguai', '60+', 'https://letzplay.me/luisafarahs'),
  ('Guilherme Valias Schmitt', 'Paraguai', '60+', 'https://letzplay.me/GuilhermeSchmitt4'),
  ('Karina Farah', 'Paraguai', '60+', 'https://letzplay.me/KarinaFarah'),
  ('Sonyangela Imai Rossi', 'Paraguai', '60+', 'https://letzplay.me/SonyangelaRossi'),
  ('Viviane Macedo Ribeiro', 'Cabo Verde', '60+', 'https://letzplay.me/VivianeRibeiro8'),
  ('Grilo .', 'Cabo Verde', '60+', 'https://letzplay.me/Grilo'),
  ('Suellen Aymore', 'Cabo Verde', '60+', 'https://letzplay.me/SuellenAymore'),
  ('Dayane Noda Kondo Rolim', 'Portugal', '60+', 'https://letzplay.me/DayaneRolim'),
  ('Alana Homrich', 'Portugal', '60+', 'https://letzplay.me/AlanaHomrich'),
  ('André Pinheiro Machado Roos', 'Portugal', '60+', 'https://letzplay.me/AndreRoos'),
  ('Edgar Martins', 'Portugal', '60+', 'https://letzplay.me/EdgarMartins'),
  ('Ana Flávia Lopes', 'USA', '60+', 'https://letzplay.me/AnaLopes25'),
  ('Amanda Mazini', 'USA', '60+', 'https://letzplay.me/AmandaMazini'),
  ('Gislaine Camargo', 'USA', '60+', 'https://letzplay.me/GislaineCamargo1'),
  ('Lilian Francisco', 'Noruega', '60+', 'https://letzplay.me/LilianFrancisco2'),
  ('Gisele Azevedo', 'Noruega', '60+', 'https://letzplay.me/GiseleDuarte2'),
  ('Bruno Okuma', 'Noruega', '60+', 'https://letzplay.me/BrunoOkuma'),
  ('Marcio Moreto', 'Noruega', '60+', 'https://letzplay.me/MarcioMoreto1'),
  ('Felipe Jardim', 'Aruba', '60+', 'https://letzplay.me/FelipeJardim5'),
  ('Gabriel Motta', 'Aruba', '60+', 'https://letzplay.me/GabrielMotta8'),
  ('Carol Soares', 'Aruba', '60+', 'https://letzplay.me/CarolinaSoares8'),
  ('Emilia Coutto', 'Aruba', '60+', 'https://letzplay.me/EmiliaCoutto'),
  ('Carlos Correia', 'Aruba', '60+', 'https://letzplay.me/CarlosAlbertoCorreia'),
  ('Gustavo Alencar', 'Cabo Verde', 'E', 'https://letzplay.me/SEPGustavoAlencar'),
  ('Livia Fanhani', 'Cabo Verde', 'E', 'https://letzplay.me/LiviaFanhani'),
  ('Enzo Martins Nelli', 'Cabo Verde', 'E', 'https://letzplay.me/EnzoNelli3'),
  ('Gustavo Pizaia', 'Cabo Verde', 'E', 'https://letzplay.me/Gustavopizaia2'),
  ('Livia Queiros Lopes', 'Cabo Verde', 'E', 'https://letzplay.me/liviaLopes26'),
  ('Guto Bento', 'Cabo Verde', 'E', 'https://letzplay.me/GutoBento'),
  ('Isabelli Franzo', 'Cabo Verde', 'E', 'https://letzplay.me/Isabellifranzo'),
  ('Fabiana De Paula', 'Portugal', 'E', 'https://letzplay.me/FabianaPaula5'),
  ('Maiara Kelm Martins', 'Portugal', 'E', 'https://letzplay.me/MaiaraMartins2'),
  ('Erica Tristao', 'Portugal', 'E', 'https://letzplay.me/EricaTristao'),
  ('Rolim Valerio', 'Portugal', 'E', 'https://letzplay.me/RolimValerio'),
  ('Miguel Bufara', 'Portugal', 'E', 'https://letzplay.me/MiguelBufara'),
  ('Vinicius Fernandes', 'Portugal', 'E', 'https://letzplay.me/ViniciusFernandes48'),
  ('Jamille Goncalves', 'Brasil', 'E', 'https://letzplay.me/JamilleFreitas'),
  ('Nagila Morais', 'Brasil', 'E', 'https://letzplay.me/NagilaMorais'),
  ('Nicolle Ohara', 'Brasil', 'E', 'https://letzplay.me/nicolle_ohara'),
  ('Gustavo Felipe', 'Brasil', 'E', 'https://letzplay.me/Gustavofelipe12'),
  ('Ricardo Ortega Rodrigues', 'Brasil', 'E', 'https://letzplay.me/RicardoOrtegaRodrigues'),
  ('Fernando Bukovski', 'Brasil', 'E', 'https://letzplay.me/FernandoBukovski1'),
  ('Gabriel Cerezini', 'Brasil', 'E', 'https://letzplay.me/GabrielCerezini'),
  ('Bruna Furio Marques Yano', 'Argentina', 'E', 'https://letzplay.me/BrunaYano'),
  ('Harumi Chimada Yano', 'Argentina', 'E', 'https://letzplay.me/Harumi'),
  ('Vitoria Atsuio Yano', 'Argentina', 'E', 'https://letzplay.me/VitoriaAtsuioYano'),
  ('Sidney Matheus', 'Argentina', 'E', 'https://letzplay.me/SidneyMatheus'),
  ('Allan Minato', 'Argentina', 'E', 'https://letzplay.me/AllanMinato'),
  ('Maria Clara Sugigan', 'Noruega', 'E', 'https://letzplay.me/MariaClaraSugigan'),
  ('Carolina Neta', 'Noruega', 'E', 'https://letzplay.me/CarolinaNeta'),
  ('Yasmin Ávila Mistrello', 'Noruega', 'E', 'https://letzplay.me/YasminMistrello'),
  ('Gabriel Lopes', 'Noruega', 'E', 'https://letzplay.me/GabrielLopes33'),
  ('Gabriel Galdino', 'Noruega', 'E', 'https://letzplay.me/GabrielGaldino4'),
  ('Igor De Oliveira', 'Noruega', 'E', 'https://letzplay.me/IgorOliveira'),
  ('Eduardo Garcia', 'Noruega', 'E', 'https://letzplay.me/Eduardocatabriga'),
  ('Caio Belli', 'Aruba', 'E', 'https://letzplay.me/caiobelli'),
  ('Guilherme Zimmermann', 'Aruba', 'E', 'https://letzplay.me/guilhermeZimmermann4'),
  ('Monica Assis', 'Aruba', 'E', 'https://letzplay.me/MonicaAssis1'),
  ('Livia Bernardelli', 'Aruba', 'E', 'https://letzplay.me/LiviaBernardelli1'),
  ('Miguel Corsini', 'Aruba', 'E', 'https://letzplay.me/MiguelCorsini2'),
  ('Miguel Moreira', 'Aruba', 'E', 'https://letzplay.me/MiguelMoreira03'),
  ('Gabriela Bernardelli', 'Aruba', 'E', 'https://letzplay.me/GabrielaBernardelli1'),
  ('Joás Vieira', 'USA', 'E', 'https://letzplay.me/JoasVieira'),
  ('Windson Lima', 'USA', 'E', 'https://letzplay.me/WindsonLima'),
  ('Vinícius Hoffmann', 'USA', 'E', 'https://letzplay.me/MarcosViniciusHoffmann'),
  ('Camilla Obo', 'USA', 'E', 'https://letzplay.me/camillaobo'),
  ('Vitoria Batista', 'USA', 'E', 'https://letzplay.me/VitoriaBatista2'),
  ('Thiago Alfredo Pereira da Silva', 'Paraguai', 'C', 'https://letzplay.me/ThiagoSilva4'),
  ('Ricardo Pariz Franciscatto', 'Paraguai', 'C', 'https://letzplay.me/RicardoFranciscatto'),
  ('Edcleide Alves Lima', 'Paraguai', 'C', 'https://letzplay.me/EdcleideLima'),
  ('Marco Drugovich', 'Paraguai', 'C', 'https://letzplay.me/MarcoDrugovich'),
  ('Murilo Viza', 'Paraguai', 'C', 'https://letzplay.me/MuriloViza1'),
  ('Camila Botelho Camargo Crupinsqui', 'Paraguai', 'C', 'https://letzplay.me/CamilaBotelho'),
  ('Maiara Frasson', 'Paraguai', 'C', 'https://letzplay.me/MaiaraCordeiro'),
  ('Carolina Milanezi Bortolon', 'Paraguai', 'C', 'https://letzplay.me/CarolBortolon'),
  ('Talitha Lunardelli', 'Cabo Verde', 'C', 'https://letzplay.me/TalithaLunardelli'),
  ('Mariana Caparroz', 'Cabo Verde', 'C', 'https://letzplay.me/MarianaCaparroz1'),
  ('Jefferson De Macedo', 'Cabo Verde', 'C', 'https://letzplay.me/JeffersonDeMacedo'),
  ('Tiago Tomaz da Rosa', 'Cabo Verde', 'C', 'https://letzplay.me/TiagoRosa11'),
  ('Andréia Teixeira', 'Cabo Verde', 'C', 'https://letzplay.me/AndreiaSantos9'),
  ('Léo Xavier', 'Cabo Verde', 'C', 'https://letzplay.me/Leoxavierr'),
  ('Rick Barbosa', 'Portugal', 'C', 'https://letzplay.me/RickBarbosa'),
  ('Guilherme Ferro', 'Portugal', 'C', 'https://letzplay.me/GuilhermeFerro1'),
  ('Renan André Pereira', 'Portugal', 'C', 'https://letzplay.me/Renanbey'),
  ('Malu Mondadori', 'Portugal', 'C', 'https://letzplay.me/MaluMondadori'),
  ('Poline Wilke', 'Portugal', 'C', 'https://letzplay.me/PolineWilke1'),
  ('Beatriz Mors', 'Portugal', 'C', 'https://letzplay.me/BeatrizMors'),
  ('Amanda Felix', 'Brasil', 'C', 'https://letzplay.me/Amandafelix6'),
  ('Pamela Franco', 'Brasil', 'C', 'https://letzplay.me/paamfranco'),
  ('Jéssika Machado', 'Brasil', 'C', 'https://letzplay.me/JessikaMachado'),
  ('Renato Meireles Pereira', 'Brasil', 'C', 'https://letzplay.me/RenatoPereira31'),
  ('Jonathan Silva Santos', 'Brasil', 'C', 'https://letzplay.me/JonathanSantos11'),
  ('Felipe Carvalho', 'Brasil', 'C', 'https://letzplay.me/FelipeCarvalho07'),
  ('Estefânia Castelini', 'Argentina', 'C', 'https://letzplay.me/EstefaniaCastelini'),
  ('Paola Sander', 'Argentina', 'C', 'https://letzplay.me/PaolaSander'),
  ('Heide Kondo', 'Argentina', 'C', 'https://letzplay.me/HeideKondo'),
  ('Lays Vedovoto', 'Argentina', 'C', 'https://letzplay.me/LaysVedovoto'),
  ('Pablo Pietro', 'Argentina', 'C', 'https://letzplay.me/PabloPietro'),
  ('João Espolador', 'Argentina', 'C', 'https://letzplay.me/JoaoEspolador'),
  ('Murilo Santana Ferraro', 'Argentina', 'C', 'https://letzplay.me/MuriloFerraro'),
  ('Luan Fonseca', 'Argentina', 'C', 'https://letzplay.me/luanfonseca1'),
  ('Junior Cezar', 'Noruega', 'C', 'https://letzplay.me/JuniorCezar2'),
  ('Laís Bianca Mendes', 'Noruega', 'C', 'https://letzplay.me/Laisbiancamendes'),
  ('Daniela Lara Lara', 'Noruega', 'C', 'https://letzplay.me/DanielaLaraLara'),
  ('Natalia Garcia Suter', 'Noruega', 'C', 'https://letzplay.me/NataliaSuter'),
  ('Giselle Correia', 'Noruega', 'C', 'https://letzplay.me/GiselleCorreia'),
  ('Augusto Pelegrino', 'Noruega', 'C', 'https://letzplay.me/AugustoPelegrino'),
  ('Hugo Okuma', 'Noruega', 'C', 'https://letzplay.me/HugoOkuma1'),
  ('Alex Eiras', 'Aruba', 'C', 'https://letzplay.me/Alexeiras1'),
  ('Fernando Russi', 'Aruba', 'C', 'https://letzplay.me/FernandoRussi1'),
  ('Nicoline Prefeito', 'Aruba', 'C', 'https://letzplay.me/MatheusNicolini1'),
  ('Nicolas Funayama', 'Aruba', 'C', 'https://letzplay.me/NicolasFunayama1'),
  ('Marina Rodrigues', 'Aruba', 'C', 'https://letzplay.me/MarinaRodrigues17'),
  ('Pietra Vendruscolo', 'Aruba', 'C', 'https://letzplay.me/PietraVendruscolo'),
  ('Diony Willian Mazini', 'USA', 'C', 'https://letzplay.me/DionyMazini'),
  ('Matheus Henrique Malvezzi', 'USA', 'C', 'https://letzplay.me/MatheusMalvezzi'),
  ('Debora Meretka', 'USA', 'C', 'https://letzplay.me/DeboraMeretka'),
  ('Kauany Marchi', 'USA', 'C', 'https://letzplay.me/KauanyMarchi'),
  ('Pietra Lorenza Barreto Lima Silva', 'USA', 'C', 'https://letzplay.me/pietraLorenza5'),
  ('Pedro Moreira', 'USA', 'C', 'https://letzplay.me/PedroMoreira33'),
  ('Lorenzo Marques', 'Cabo Verde', 'D', 'https://letzplay.me/lorenzoMarques6'),
  ('Patrícia Gomes', 'Cabo Verde', 'D', 'https://letzplay.me/PatriciaGomes7'),
  ('Fernanda Proença', 'Cabo Verde', 'D', 'https://letzplay.me/FernandaProenca'),
  ('Gustavo Shira', 'Cabo Verde', 'D', 'https://letzplay.me/Shira'),
  ('Beatriz Rosada', 'Cabo Verde', 'D', 'https://letzplay.me/BeatrizRosada'),
  ('Pietro Lepri', 'Cabo Verde', 'D', 'https://letzplay.me/PietroLepri'),
  ('Georgia Bufara', 'Portugal', 'D', 'https://letzplay.me/GeorgiaBufara2'),
  ('Cíntia Bresciani', 'Portugal', 'D', 'https://letzplay.me/CintiaSibert'),
  ('Dayane Noda Kondo Rolim', 'Portugal', 'D', 'https://letzplay.me/DayaneRolim'),
  ('Bernardo Inocente', 'Portugal', 'D', 'https://letzplay.me/BInocente'),
  ('Edgar Martins', 'Portugal', 'D', 'https://letzplay.me/EdgarMartins'),
  ('Taila Alher', 'Brasil', 'D', 'https://letzplay.me/tailaalher'),
  ('Jessica De Souza da Silva', 'Brasil', 'D', 'https://letzplay.me/Jessicasilva116'),
  ('Victoria Carolini', 'Brasil', 'D', 'https://letzplay.me/victoriacarolini'),
  ('Miranda G', 'Brasil', 'D', 'https://letzplay.me/Gmirandaa'),
  ('Wesley Lima', 'Brasil', 'D', 'https://letzplay.me/Wesleylima12'),
  ('Kaue Silva', 'Brasil', 'D', 'https://letzplay.me/KaueSilva12'),
  ('Rafael Storti', 'Brasil', 'D', 'https://letzplay.me/RafaelStorti1'),
  ('Paula Da Silva', 'Argentina', 'D', 'https://letzplay.me/Paulasilva58'),
  ('Naiara Gomes', 'Argentina', 'D', 'https://letzplay.me/NaiaraGomes2'),
  ('Kadu Borba', 'Argentina', 'D', 'https://letzplay.me/CarlosRezende12'),
  ('Gustavo Pontes', 'Argentina', 'D', 'https://letzplay.me/Gustavopontes11'),
  ('Thiago Turci', 'Argentina', 'D', 'https://letzplay.me/ThiagoTurci'),
  ('Mateus Tavares', 'Argentina', 'D', 'https://letzplay.me/mateustavares2012'),
  ('Rayane Costa', 'Argentina', 'D', 'https://letzplay.me/RayaneCosta2'),
  ('Luanna Ribas', 'Noruega', 'D', 'https://letzplay.me/Luannaribas'),
  ('Lorena Martins Baia', 'Noruega', 'D', 'https://letzplay.me/LorenaMartinsbaia'),
  ('Ana Paula da Silva Souza', 'Noruega', 'D', 'https://letzplay.me/AnaSouza71'),
  ('Gisele Azevedo', 'Noruega', 'D', 'https://letzplay.me/GiseleDuarte2'),
  ('Kader Ferraresi', 'Noruega', 'D', 'https://letzplay.me/kaderferraresi'),
  ('Marcos Queiroz', 'Noruega', 'D', 'https://letzplay.me/MarcosQueiroz'),
  ('Bruno Okuma', 'Noruega', 'D', 'https://letzplay.me/BrunoOkuma'),
  ('Alexis Prado Constantinopolos', 'Noruega', 'D', 'https://letzplay.me/Alexispolos'),
  ('Felipe Barcaro', 'Aruba', 'D', 'https://letzplay.me/FelipeBarcaro1'),
  ('Miguel Struckel', 'Aruba', 'D', 'https://letzplay.me/MiguelStruckel1'),
  ('Maria Eloisa Ceranto', 'Aruba', 'D', 'https://letzplay.me/MariaEloisaCeranto3'),
  ('Brenda Ferrari', 'Aruba', 'D', 'https://letzplay.me/BrendaFerrari'),
  ('Miguel Aguiar', 'Aruba', 'D', 'https://letzplay.me/MiguelAguiar5'),
  ('Maria Beatriz Ceranto', 'Aruba', 'D', 'https://letzplay.me/MariaBeatrizCeranto4'),
  ('Fabio Gustavo', 'USA', 'D', 'https://letzplay.me/FabioGustavo1'),
  ('Mateus Verhalen Corrêa', 'USA', 'D', 'https://letzplay.me/MateusCorrea5'),
  ('João Guilherme De Matos', 'USA', 'D', 'https://letzplay.me/JoaoGuilhermedeMatos'),
  ('Renata Rufato', 'USA', 'D', 'https://letzplay.me/RenataRufato'),
  ('Nicole Asse', 'USA', 'D', 'https://letzplay.me/NicoleAsse'),
  ('Alberto Vinícius Rodrigues Lima', 'Paraguai', 'A', 'https://letzplay.me/AlbertoViniciusLima'),
  ('Daniel Felipe Faleiro', 'Paraguai', 'A', 'https://letzplay.me/DanielFaleiro'),
  ('Faena Gabriela Ehlers', 'Paraguai', 'A', 'https://letzplay.me/faenaehlers'),
  ('Guilherme Valias Schmitt', 'Paraguai', 'A', 'https://letzplay.me/GuilhermeSchmitt4'),
  ('Joao Caldeirao', 'Paraguai', 'A', 'https://letzplay.me/JoaoCaldeirao'),
  ('Karina Farah', 'Paraguai', 'A', 'https://letzplay.me/KarinaFarah'),
  ('Luísa Farah', 'Paraguai', 'A', 'https://letzplay.me/luisafarahs'),
  ('Marcela Santos', 'Paraguai', 'A', 'https://letzplay.me/Marcelasantoss'),
  ('Ubiara Rubio Engler', 'Cabo Verde', 'A', 'https://letzplay.me/UbiaraEngler'),
  ('Luiz Petita', 'Cabo Verde', 'A', 'https://letzplay.me/LuizPetita'),
  ('Mateus Petita', 'Cabo Verde', 'A', 'https://letzplay.me/MateusPetita1'),
  ('Bianca Mors', 'Portugal', 'A', 'https://letzplay.me/BiancaMors'),
  ('Daiane Franciele Camargo', 'Portugal', 'A', 'https://letzplay.me/DaianeFrancieleCamargo'),
  ('Pedro Lucas', 'Portugal', 'A', 'https://letzplay.me/PedroGoncalves17'),
  ('Filipe Gomes', 'Portugal', 'A', 'https://letzplay.me/FilipeGomes4'),
  ('Lucas Mengue', 'Brasil', 'A', 'https://letzplay.me/LucasMengue'),
  ('Ronnie Junior', 'Brasil', 'A', 'https://letzplay.me/RonnieJunior1'),
  ('Ana Gabriela', 'Brasil', 'A', 'https://letzplay.me/AnaGabrielaRomao'),
  ('Agar Souza', 'Brasil', 'A', 'https://letzplay.me/AgarSouza'),
  ('Diogo Diornellas', 'Argentina', 'A', 'https://letzplay.me/DiornellasDiogo'),
  ('Leandro Proença', 'Argentina', 'A', 'https://letzplay.me/LeandroProenca'),
  ('Renata Fernandes', 'Noruega', 'A', 'https://letzplay.me/RenataFernandes50'),
  ('Ale Manzotti', 'Noruega', 'A', 'https://letzplay.me/AleManzotti1'),
  ('Giovanni Russi', 'Noruega', 'A', 'https://letzplay.me/GiovanniRussi2'),
  ('Lilian Francisco', 'Noruega', 'A', 'https://letzplay.me/LilianFrancisco2'),
  ('Evelyn Costa', 'Noruega', 'A', 'https://letzplay.me/EvelynCosta6'),
  ('Sthefani Depieri', 'Aruba', 'A', 'https://letzplay.me/SthefaniDepieri'),
  ('Lara Perez', 'Aruba', 'A', 'https://letzplay.me/LaraPerez'),
  ('Gabriel Motta', 'Aruba', 'A', 'https://letzplay.me/GabrielMotta8'),
  ('Gustavo Coutto', 'Aruba', 'A', 'https://letzplay.me/GustavoSantos99'),
  ('Felipe Jardim', 'Aruba', 'A', 'https://letzplay.me/FelipeJardim5'),
  ('Rafael Nadal', 'USA', 'A', 'https://letzplay.me/RafaelNadal7'),
  ('Amnon Felipe', 'USA', 'A', 'https://letzplay.me/amnonpasetofelipe'),
  ('Ana Flávia Lopes', 'USA', 'A', 'https://letzplay.me/AnaLopes25'),
  ('Amanda Mazini', 'USA', 'A', 'https://letzplay.me/AmandaMazini'),
  ('João Calado', 'USA', 'A', 'https://letzplay.me/JoaoCalado3'),
  ('Ana Clara Monteiro Marchini', 'Paraguai', 'B', 'https://letzplay.me/AnaClaraMarchini1'),
  ('Ana Aguilar', 'Paraguai', 'B', 'https://letzplay.me/AnaAguilar'),
  ('Arthur Mendes', 'Paraguai', 'B', 'https://letzplay.me/ArthurMendes'),
  ('Danilo Braga', 'Paraguai', 'B', 'https://letzplay.me/DaniloBraga1'),
  ('Gabriela Rezende', 'Paraguai', 'B', 'https://letzplay.me/GabrielaRezende12'),
  ('Joata Campetti', 'Paraguai', 'B', 'https://letzplay.me/JoataCampetti'),
  ('Luiz Antônio Fidelis', 'Paraguai', 'B', 'https://letzplay.me/LuizAntonioFidelis'),
  ('Rodrigo Vicentini', 'Cabo Verde', 'B', 'https://letzplay.me/RodrigoVicentini'),
  ('Gabriela Duarte Milani de Holanda', 'Cabo Verde', 'B', 'https://letzplay.me/GabrielaDuarteHolanda'),
  ('Jheniffer Venciguerra', 'Cabo Verde', 'B', 'https://letzplay.me/JhenifferVenciguerra'),
  ('Ryan Augusto dos Santos', 'Cabo Verde', 'B', 'https://letzplay.me/Ryan'),
  ('Wesley Crupinsqui', 'Cabo Verde', 'B', 'https://letzplay.me/WesleyCrupinsqui'),
  ('Max Jardim', 'Portugal', 'B', 'https://letzplay.me/MaxJardim2'),
  ('Gabriel Lopes', 'Portugal', 'B', 'https://letzplay.me/GabrielLopesbt'),
  ('Rafael Camargo', 'Portugal', 'B', 'https://letzplay.me/RafaelCamargo36'),
  ('Leticia Mendonsa', 'Portugal', 'B', 'https://letzplay.me/LeticiaMendonsa'),
  ('Jenifer Matter', 'Portugal', 'B', 'https://letzplay.me/JeniferMatter'),
  ('Lorena Castagna Angelim Costa', 'Portugal', 'B', 'https://letzplay.me/LorenaCosta17'),
  ('Joao Paulo', 'Brasil', 'B', 'https://letzplay.me/Jpsiilvaa'),
  ('Lívia De Souza Cardoso', 'Brasil', 'B', 'https://letzplay.me/LiviaCardoso12'),
  ('João Victor Melo', 'Brasil', 'B', 'https://letzplay.me/JoaoV'),
  ('Paulo Roberto', 'Brasil', 'B', 'https://letzplay.me/PauloRobertoGermanoDosSantos'),
  ('Taline Mangolin', 'Brasil', 'B', 'https://letzplay.me/TalineMangolin'),
  ('Rafaela Lenardon', 'Argentina', 'B', 'https://letzplay.me/RafaelaLenardon'),
  ('Carolyne Balan', 'Argentina', 'B', 'https://letzplay.me/CarolyneBalan'),
  ('Carolina Genofre', 'Argentina', 'B', 'https://letzplay.me/CarolinaVecchiaGenofre'),
  ('Vitor Zumas', 'Argentina', 'B', 'https://letzplay.me/VitorZumas'),
  ('Bicaio Bicaio', 'Argentina', 'B', 'https://letzplay.me/bicaiio'),
  ('João Gabriel Aguiar', 'Argentina', 'B', 'https://letzplay.me/JoaoGabrielAguiar3'),
  ('Gustavo Oliveira', 'Argentina', 'B', 'https://letzplay.me/gustavooliveira211'),
  ('Pedro Castro', 'Noruega', 'B', 'https://letzplay.me/PedroCastro67'),
  ('Daiana Cristian', 'Noruega', 'B', 'https://letzplay.me/DaianaCristian'),
  ('Armando Felix', 'Noruega', 'B', 'https://letzplay.me/ArmandoFelix1'),
  ('Marcio Moreto', 'Noruega', 'B', 'https://letzplay.me/MarcioMoreto1'),
  ('Josy Graca', 'Noruega', 'B', 'https://letzplay.me/JosyGraca1'),
  ('Maria Clara Lopes', 'Noruega', 'B', 'https://letzplay.me/MariaClaraLopes14'),
  ('Thiago Garcia', 'Noruega', 'B', 'https://letzplay.me/ThiagoGarcia07'),
  ('Samuel Ribeiro', 'Aruba', 'B', 'https://letzplay.me/SamuelRibeiro18'),
  ('Daniel Souza', 'Aruba', 'B', 'https://letzplay.me/DanielSouza54'),
  ('Amabile Zolin Deantoni', 'Aruba', 'B', 'https://letzplay.me/amabilezd'),
  ('Beatriz Cazon', 'Aruba', 'B', 'https://letzplay.me/BeatrizCazon3'),
  ('Gabriela Zilioto', 'Aruba', 'B', 'https://letzplay.me/GabrielaZiliotto3'),
  ('Miguel Souza', 'Aruba', 'B', 'https://letzplay.me/Miguelsouza33'),
  ('Luiz Henrique Leandro', 'USA', 'B', 'https://letzplay.me/LuizHenriqueLeandro'),
  ('Mayke Pereira Arruda', 'USA', 'B', 'https://letzplay.me/MaykeArruda'),
  ('Pedro Neto', 'USA', 'B', 'https://letzplay.me/PedroNeto83'),
  ('Rafael Piffer', 'USA', 'B', 'https://letzplay.me/RafaelPiffer'),
  ('Julia Mello', 'USA', 'B', 'https://letzplay.me/JuliaMello11'),
  ('Lara Laino', 'USA', 'B', 'https://letzplay.me/LaraTonon'),
  ('Sofia Asse', 'USA', 'B', 'https://letzplay.me/SofiaEvangelista1')
)
insert into public.athlete_registrations (athlete_id, team_id, team_name, category_name, letzplay_profile)
select a.id, t.id, s.team_name, s.category_name, s.letzplay_profile from source s
join public.teams t on t.team_name = s.team_name
join public.athletes a on a.team_id = t.id and lower(trim(a.athlete_name)) = lower(trim(s.athlete_name));


